using System;
using System.Data;
using System.Collections.Immutable;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Scripting.Js.v1;
using CSharpFunctionalExtensions;
using System.IO;
using System.Threading;

namespace Scripting.Tests
{
    [TestClass]
    public class ES6_Scripting_InMemoryFiles_Tests
    {
        [TestMethod]
        public void ClearScript_Scripting_InMemoryFiles_Test()
        {
            //Assert.Inconclusive(); return;

            ScriptingContext jsScriptingContext = ScriptingContext.ScriptingContextWithInMemoryFs(ES6_scripts_to_zip_plus_to_encode_in_Base64.GetScripts());

            JsScriptRunner jsScriptRunner = JsScriptRunner.RunnerWithContext(
                //JsScriptRunnerType.ClearScriptDebugMode,  // to debug
                JsScriptRunnerType.ClearScript,  // to execute without debugging
                jsScriptingContext,
                Scripting_TestSettings.ScriptingContextName);

            jsScriptRunner.Run("var exports = {};");  // required by the row of 'main.js' ```Object.defineProperty(exports, "__esModule", { value: true });``` generated by TypeScript
            jsScriptRunner.Run(jsScriptingContext.ReadFile("./lib/myrequire.js"));  // load a custom version of 'require'
            jsScriptRunner.Run(jsScriptingContext.ReadFile("main.js"));  // execute script from virtual FS (would have been the same executing "./main.js")
            Assert.AreEqual("Hello World", jsScriptingContext.ReadFile("filename"));  // test output of Js scripts
        }
    }
}
